#ifndef BOARD_INFO_H
#define BOARD_INFO_H

#include "soc/gpio_num.h"

#define SERIAL_TX_PIN GPIO_NUM_43
#define SERIAL_RX_PIN GPIO_NUM_44

#define CAM_SIOD_PIN GPIO_NUM_4
#define CAM_SIOC_PIN GPIO_NUM_5
#define CAM_VSYNC_PIN GPIO_NUM_6
#define CAM_HERF_PIN GPIO_NUM_7
#define CAM_XCLK_PIN GPIO_NUM_15
#define CAM_Y9_PIN GPIO_NUM_16
#define CAM_Y8_PIN GPIO_NUM_17
#define CAM_Y7_PIN GPIO_NUM_18
#define CAM_Y4_PIN GPIO_NUM_8
#define STRAPPING_0_PIN GPIO_NUM_3
#define STRAPPING_1_PIN GPIO_NUM_46
#define CAM_Y3_PIN GPIO_NUM_9
#define CAM_Y5_PIN GPIO_NUM_10
#define CAM_Y2_PIN GPIO_NUM_11
#define CAM_Y6_PIN GPIO_NUM_12
#define CAM_PCLK_PIN GPIO_NUM_13
#define IIS_BCK_PIN GPIO_NUM_14
#define IIC_SCL_PIN GPIO_NUM_1
#define IIC_SDA_PIN GPIO_NUM_2
#define IIS_LCK_PIN GPIO_NUM_42
#define IIS_DIN_PIN GPIO_NUM_41
#define SD_DATA_PIN GPIO_NUM_40
#define SD_CLK_PIN GPIO_NUM_39
#define SD_CMD_PIN GPIO_NUM_38
#define PSRAM_0_PIN GPIO_NUM_37
#define PSRAM_1_PIN GPIO_NUM_36
#define PSRAM_2_PIN GPIO_NUM_35
#define TFT_DC_PIN GPIO_NUM_0
#define STRAPPING_2_PIN GPIO_NUM_45
#define WS2812_PIN GPIO_NUM_48
#define TFT_CS_PIN GPIO_NUM_47
#define TFT_SCK_PIN GPIO_NUM_21
#define TFT_MOSI_PIN GPIO_NUM_20
#define BAT_ADC_PIN GPIO_NUM_19

#define LCD_H_RES 240
#define LCD_V_RES 320
#define LCD_PIXEL_CLOCK_HZ (40 * 1000 * 1000) // 40 MHz clock speed
#define LCD_CMD_BITS 8
#define LCD_PARAM_BITS 8

#endif // BOARD_INFO_H